-- SUPERSEDED. Do not run this file.
-- The complete, re-runnable schema is supabase/schema.sql (profiles, crops,
-- listings, storage, admin). This file used to contain an unguarded
-- "create table profiles", which fails with 42P07 on an existing database.
